### ISSUE TITLE
Error in histogram visualization

### ISSUE THREAD

**Issue by TatiKolpakova** [r-classes/ds4dh-hw1-TatiKolpakova#1]
Using this code, I tried to visualize data in the form of a histogram based on Freedman, Diaconis algorithm. Why does R throw the error: 

> Error in signif(x, digits = 5) : 
non-numeric argument to mathematical function
In addition: Warning message:
Unknown or uninitialised column: 'mtcars'
```
dput(head(mtcars,2))
structure(list(mpg = c(21, 21), cyl = c(6, 6), 
               disp = c(160, 160),
               hp = c(110, 110), drat = c(3.9, 3.9),
               wt = c(2.62, 2.875), qcec = c(16.46, 17.02), 
               vs = c(0, 0), am =c(1, 1),
               gear = c(4, 4), carb = c(4, 4)),
          row.names = c("Mazda RX4", "Mazda RX4 Wag"), 
          class = "data.frame")
mtcars %>% 
ggplot(aes(mpg)) +
geom_histogram(bins = nclass.FD(mpg$mtcars))
 
sessionInfo()$R.version$version.string
```

**Comment by agricolamz** [comment]
Hi, could you please format code in a better way and provide explanation, what you'd expected.

**Comment by TatiKolpakova** [comment]
Hi, sorry for the previous version of the code - formatting failed. Using this code, I tried to create a histogram with based on the Freedman, Diaconis algorithm.

**Comment by TatiKolpakova** [comment]
Hi, I'm sorry for the previous version of the code - formatting failed. Using this code, I tried to create a histogram with based on the Freedman, Diaconis algorithm.

**Comment by TatiKolpakova** [comment]
Hi, I'm sorry for the previous version of code - formatting failed. Using this code, I tried to create a histogram with based on Freedman and Diaconis algorithm.

**Comment by TatiKolpakova** [comment]
Hi, @agricolamz , I'm sorry for the previous version of the code - formatting failed. Using this code, I tried to visualize data in the form of a histogram based on Freedman, Diaconis algorithm.

**Comment by TatiKolpakova** [comment]
Hi, @agricolamz , I'm sorry for the previous version of the code - formatting failed and I didn’t explain my problem in detail — added a description.

**Comment by agricolamz** [comment]
Hi, it looks like you confused data.frame and its variable: `nclass.FD(mpg$mtcars)`. It should be `nclass.FD(mtcars$mpg)`.
